function reportPath = generateReport(screening, patientInfo, cfg)
% generateReport  Creates an HTML screening report from pipeline results.
%
%   reportPath = generateReport(screening, patientInfo, cfg)
%
%   Input:
%     screening   - output of runScreeningPipeline()
%     patientInfo - struct with:
%                   .patientID, .examinationID, .eye, .date
%                   .imageSource   (optional)
%     cfg         - RGConfig() struct
%
%   Output:
%     reportPath  - full path to the generated HTML report
%
%   The report is saved to cfg.paths.reports.
%   PDF export can be triggered from the MATLAB App using a print command.

if nargin < 3, cfg = RGConfig(); end

% ---- Ensure reports directory exists --------------------------------
if ~isfolder(cfg.paths.reports)
    mkdir(cfg.paths.reports);
end

% ---- Report filename ------------------------------------------------
ts        = datestr(now, 'yyyymmdd_HHMMSS');
reportFn  = sprintf('RetinaGuard_Report_%s_%s.html', patientInfo.examinationID, ts);
reportPath = fullfile(cfg.paths.reports, reportFn);

% ---- Helpers --------------------------------------------------------
function s = fmtDetected(detected, confidence)
    if detected
        s = sprintf('<span class="finding-yes">Detected</span> <span class="conf">%.0f%%</span>', confidence*100);
    else
        s = sprintf('<span class="finding-no">Not detected</span> <span class="conf">%.0f%%</span>', confidence*100);
    end
end

function s = qualBadge(status)
    switch status
        case 'GOOD',        s = '<span class="badge-good">GOOD</span>';
        case 'BORDERLINE',  s = '<span class="badge-borderline">BORDERLINE</span>';
        otherwise,          s = '<span class="badge-ungradable">UNGRADABLE</span>';
    end
end

function s = gradeColor(grade)
    colors = {'#2d7a2d','#c47d00','#c47d00','#b53000','#8b0000'};
    if grade >= 0 && grade <= 4
        s = colors{grade+1};
    else
        s = '#555555';
    end
end

function s = confBadge(level)
    switch level
        case 'high',     s = '<span class="badge-high-conf">HIGH CONFIDENCE</span>';
        case 'moderate', s = '<span class="badge-mod-conf">MODERATE CONFIDENCE</span>';
        otherwise,       s = '<span class="badge-low-conf">LOW CONFIDENCE</span>';
    end
end

% ---- Get grading info -----------------------------------------------
q = screening.quality;
g = screening.grading;
l = screening.lesions;
st = screening.structures;

gradeName  = 'Not graded';
shortGrade = 'N/A';
confLevel  = 'low';
confVal    = 0;
referralTx = 'Unable to grade — please recapture image.';

if ~isempty(g)
    gradeName  = g.label;
    shortGrade = g.shortLabel;
    confLevel  = g.confidenceLevel;
    confVal    = g.confidence;
    referralTx = g.referralText;
end

demoNote = '';
if isempty(g) || g.demoMode
    demoNote = '<div class="demo-banner">⚠ DEMO RESULT — This report uses demonstration inference. Not medically validated.</div>';
end

% ---- Severity colour ------------------------------------------------
gradeNum = -1;
if ~isempty(g), gradeNum = g.grade; end
gradeClr = gradeColor(gradeNum);

% ---- Build HTML -----------------------------------------------------
html = ['<!DOCTYPE html>' newline ...
'<html lang="en"><head>' newline ...
'<meta charset="UTF-8">' newline ...
'<meta name="viewport" content="width=device-width, initial-scale=1.0">' newline ...
'<title>RetinaGuard Screening Report</title>' newline ...
'<style>' newline ...
'  * { box-sizing: border-box; margin: 0; padding: 0; }' newline ...
'  body { font-family: "Segoe UI", Helvetica, Arial, sans-serif; font-size:14px; color:#1a2433; background:#f4f6f8; }' newline ...
'  .page { max-width:860px; margin:0 auto; background:#fff; padding:0; }' newline ...
'  .header { background:#1b2a45; color:#fff; padding:24px 32px 20px; display:flex; justify-content:space-between; align-items:center; }' newline ...
'  .header-title { font-size:22px; font-weight:700; letter-spacing:0.5px; }' newline ...
'  .header-sub { font-size:12px; opacity:0.7; margin-top:4px; }' newline ...
'  .header-meta { text-align:right; font-size:12px; opacity:0.75; }' newline ...
'  .demo-banner { background:#7a4f00; color:#fff7e6; padding:10px 32px; font-size:13px; font-weight:600; }' newline ...
'  .section { padding:20px 32px; border-bottom:1px solid #e4e8ee; }' newline ...
'  .section-title { font-size:11px; font-weight:700; letter-spacing:1.2px; text-transform:uppercase; color:#6b7a90; margin-bottom:12px; }' newline ...
'  .grid-2 { display:grid; grid-template-columns:1fr 1fr; gap:12px; }' newline ...
'  .grid-3 { display:grid; grid-template-columns:1fr 1fr 1fr; gap:12px; }' newline ...
'  .kv { }' newline ...
'  .kv-label { font-size:11px; color:#8090a8; text-transform:uppercase; letter-spacing:0.6px; }' newline ...
'  .kv-value { font-size:14px; font-weight:600; color:#1a2433; margin-top:2px; }' newline ...
'  .severity-block { text-align:center; padding:24px; background:#f7f9fb; border:1px solid #e0e4ea; border-radius:4px; }' newline ...
'  .severity-level { font-size:13px; color:#6b7a90; font-weight:600; letter-spacing:1px; text-transform:uppercase; }' newline ...
'  .severity-grade { font-size:40px; font-weight:800; letter-spacing:-1px; }' newline ...
'  .severity-name { font-size:15px; font-weight:600; margin-top:4px; }' newline ...
'  .conf-row { margin-top:10px; font-size:13px; color:#6b7a90; }' newline ...
'  .findings-table { width:100%; border-collapse:collapse; font-size:13px; }' newline ...
'  .findings-table th { text-align:left; padding:7px 10px; font-size:11px; letter-spacing:0.8px; text-transform:uppercase; color:#6b7a90; border-bottom:1px solid #e4e8ee; }' newline ...
'  .findings-table td { padding:8px 10px; border-bottom:1px solid #f0f2f5; vertical-align:middle; }' newline ...
'  .findings-table tr:last-child td { border-bottom:none; }' newline ...
'  .finding-yes { color:#2d7a2d; font-weight:600; }' newline ...
'  .finding-no { color:#6b7a90; }' newline ...
'  .conf { font-size:12px; color:#8090a8; margin-left:6px; }' newline ...
'  .badge-good { background:#e7f5ea; color:#2d7a2d; padding:3px 10px; border-radius:3px; font-size:12px; font-weight:700; }' newline ...
'  .badge-borderline { background:#fff4e0; color:#c47d00; padding:3px 10px; border-radius:3px; font-size:12px; font-weight:700; }' newline ...
'  .badge-ungradable { background:#fde8e8; color:#b53000; padding:3px 10px; border-radius:3px; font-size:12px; font-weight:700; }' newline ...
'  .badge-high-conf { background:#e7f5ea; color:#2d7a2d; padding:3px 10px; border-radius:3px; font-size:11px; font-weight:700; }' newline ...
'  .badge-mod-conf { background:#fff4e0; color:#c47d00; padding:3px 10px; border-radius:3px; font-size:11px; font-weight:700; }' newline ...
'  .badge-low-conf { background:#fde8e8; color:#b53000; padding:3px 10px; border-radius:3px; font-size:11px; font-weight:700; }' newline ...
'  .scale-bar { display:flex; gap:0; margin-top:12px; border:1px solid #e0e4ea; border-radius:4px; overflow:hidden; }' newline ...
'  .scale-cell { flex:1; text-align:center; padding:6px 4px; font-size:11px; font-weight:600; background:#f7f9fb; color:#8090a8; }' newline ...
'  .scale-cell.active { color:#fff; }' newline ...
'  .referral-box { background:#f7f9fb; border-left:4px solid #1b5ca8; padding:14px 18px; margin-top:16px; font-size:13px; }' newline ...
'  .referral-title { font-size:11px; text-transform:uppercase; letter-spacing:0.8px; color:#6b7a90; margin-bottom:4px; }' newline ...
'  .disclaimer { background:#f4f6f8; border-top:1px solid #e4e8ee; padding:20px 32px; font-size:11px; color:#8090a8; line-height:1.6; }' newline ...
'  .footer { background:#1b2a45; color:#6e8aac; padding:14px 32px; font-size:11px; text-align:center; }' newline ...
'  .score-bar { height:6px; background:#e4e8ee; border-radius:3px; margin-top:6px; overflow:hidden; }' newline ...
'  .score-fill { height:100%; border-radius:3px; }' newline ...
'</style>' newline ...
'</head><body><div class="page">' newline];

% ---- Header ---------------------------------------------------------
html = [html ...
'<div class="header">' newline ...
'  <div>' newline ...
'    <div class="header-title">RetinaGuard</div>' newline ...
'    <div class="header-sub">AI-Assisted Retinal Screening Report</div>' newline ...
'  </div>' newline ...
'  <div class="header-meta">' newline ...
sprintf('    <div>%s</div>', patientInfo.date) newline ...
'    <div>RetinaGuard v1.0 Prototype</div>' newline ...
'  </div>' newline ...
'</div>' newline];

% ---- Demo banner ----------------------------------------------------
html = [html demoNote newline];

% ---- Patient Info ---------------------------------------------------
html = [html ...
'<div class="section">' newline ...
'  <div class="section-title">Examination Information</div>' newline ...
'  <div class="grid-3">' newline ...
sprintf('    <div class="kv"><div class="kv-label">Patient ID</div><div class="kv-value">%s</div></div>', patientInfo.patientID) newline ...
sprintf('    <div class="kv"><div class="kv-label">Examination ID</div><div class="kv-value">%s</div></div>', patientInfo.examinationID) newline ...
sprintf('    <div class="kv"><div class="kv-label">Eye</div><div class="kv-value">%s</div></div>', patientInfo.eye) newline ...
'  </div>' newline ...
'</div>' newline];

% ---- Image Quality --------------------------------------------------
if ~isempty(q)
    barColor = '#2d7a2d';
    if q.score < 60, barColor = '#c47d00'; end
    if q.score < 40, barColor = '#b53000'; end

    html = [html ...
    '<div class="section">' newline ...
    '  <div class="section-title">Image Quality Assessment</div>' newline ...
    '  <div class="grid-2">' newline ...
    '    <div>' newline ...
    sprintf('      <div class="kv"><div class="kv-label">Overall Quality</div><div class="kv-value">%s</div></div>', qualBadge(q.status)) newline ...
    sprintf('      <div class="kv" style="margin-top:10px"><div class="kv-label">Quality Score</div><div class="kv-value">%d / 100</div></div>', q.score) newline ...
    sprintf('      <div class="score-bar"><div class="score-fill" style="width:%d%%;background:%s;"></div></div>', q.score, barColor) newline ...
    '    </div>' newline ...
    '    <div>' newline ...
    sprintf('      <div class="kv"><div class="kv-label">Focus</div><div class="kv-value">%s</div></div>', q.focus) newline ...
    sprintf('      <div class="kv" style="margin-top:6px"><div class="kv-label">Illumination</div><div class="kv-value">%s</div></div>', q.illumination) newline ...
    sprintf('      <div class="kv" style="margin-top:6px"><div class="kv-label">Field of View</div><div class="kv-value">%s</div></div>', q.fieldOfView) newline ...
    sprintf('      <div class="kv" style="margin-top:6px"><div class="kv-label">Contrast</div><div class="kv-value">%s</div></div>', q.contrast) newline ...
    '    </div>' newline ...
    '  </div>' newline ...
    '</div>' newline];
end

% ---- Severity Result ------------------------------------------------
if ~isempty(g)
    scale = '';
    labels5 = {'No DR','Mild','Moderate','Severe','PDR'};
    for k = 0:4
        bg = '#f7f9fb'; fg = '#8090a8';
        if k == g.grade
            bg = gradeClr; fg = '#fff';
        end
        scale = [scale sprintf('<div class="scale-cell active" style="background:%s;color:%s;">%s</div>', bg, fg, labels5{k+1})];
    end

    html = [html ...
    '<div class="section">' newline ...
    '  <div class="section-title">DR Screening Result</div>' newline ...
    '  <div class="severity-block">' newline ...
    '    <div class="severity-level">AI-Assisted Screening Result</div>' newline ...
    sprintf('    <div class="severity-grade" style="color:%s;">Level %d</div>', gradeClr, g.grade) newline ...
    sprintf('    <div class="severity-name">%s</div>', gradeName) newline ...
    sprintf('    <div class="conf-row">Model Confidence: <strong>%.0f%%</strong>&nbsp;&nbsp;%s</div>', confVal*100, confBadge(confLevel)) newline ...
    '  </div>' newline ...
    sprintf('  <div class="scale-bar">%s</div>', scale) newline ...
    '  <div class="referral-box">' newline ...
    '    <div class="referral-title">Clinical Recommendation</div>' newline ...
    sprintf('    <div>%s</div>', referralTx) newline ...
    '  </div>' newline ...
    '</div>' newline];
end

% ---- Lesion Findings ------------------------------------------------
if ~isempty(l)
    nvRiskStr = 'Low';
    if isfield(l.neovascularization, 'riskLevel')
        nvRiskStr = l.neovascularization.riskLevel;
    end
    html = [html ...
    '<div class="section">' newline ...
    '  <div class="section-title">Lesion Candidate Analysis (Computer Vision)</div>' newline ...
    '  <table class="findings-table">' newline ...
    '    <tr><th>Lesion Type</th><th>Detection Status</th><th>Quantitative Findings / Notes</th></tr>' newline ...
    sprintf('    <tr><td>Microaneurysms</td><td>%s</td><td>Candidates: %d (Morphological top-hat analysis)</td></tr>', fmtDetected(l.microaneurysm.detected, l.microaneurysm.confidence), l.microaneurysm.count) newline ...
    sprintf('    <tr><td>Hard Exudates</td><td>%s</td><td>Candidates: %d, Area: %d px (Disc-excluded)</td></tr>', fmtDetected(l.exudate.detected, l.exudate.confidence), l.exudate.count, l.exudate.area) newline ...
    sprintf('    <tr><td>Hemorrhages</td><td>%s</td><td>Candidates: %d, Area: %d px (Dark lesion segmentation)</td></tr>', fmtDetected(l.hemorrhage.detected, l.hemorrhage.confidence), l.hemorrhage.count, l.hemorrhage.area) newline ...
    sprintf('    <tr><td>Neovascularization Risk</td><td>%s</td><td>Risk Indicator: %s (Peri-papillary vessel density)</td></tr>', fmtDetected(l.neovascularization.detected, l.neovascularization.confidence), nvRiskStr) newline ...
    '  </table>' newline ...
    '</div>' newline];
end

% ---- Structures -----------------------------------------------------
if ~isempty(st)
    odNote = 'Detected';
    if isfield(st.opticDisc, 'centroid') && ~isempty(st.opticDisc.centroid)
        odNote = sprintf('Centroid: [%.0f, %.0f], Radius: %.0f px', st.opticDisc.centroid(1), st.opticDisc.centroid(2), st.opticDisc.radius);
    end
    fvNote = 'Estimated';
    if isfield(st.fovea, 'coordinates') && ~isempty(st.fovea.coordinates)
        fvNote = sprintf('Coordinates: [%.0f, %.0f]', st.fovea.coordinates(1), st.fovea.coordinates(2));
    end
    vsNote = 'Segmented';
    if isfield(st.vessels, 'density') && ~isempty(st.vessels.density)
        vsNote = sprintf('Vessel Density: %.1f%% of retinal area', st.vessels.density);
    end

    html = [html ...
    '<div class="section">' newline ...
    '  <div class="section-title">Retinal Anatomical Landmarks</div>' newline ...
    '  <table class="findings-table">' newline ...
    '    <tr><th>Structure</th><th>Status</th><th>Localization / Measurements</th></tr>' newline ...
    sprintf('    <tr><td>Optic Disc</td><td>%s</td><td>%s</td></tr>', fmtDetected(st.opticDisc.detected, st.opticDisc.confidence), odNote) newline ...
    sprintf('    <tr><td>Fovea Centralis</td><td>%s</td><td>%s</td></tr>', fmtDetected(st.fovea.detected, st.fovea.confidence), fvNote) newline ...
    sprintf('    <tr><td>Retinal Vasculature</td><td>%s</td><td>%s</td></tr>', fmtDetected(st.vessels.detected, st.vessels.confidence), vsNote) newline ...
    '  </table>' newline ...
    '</div>' newline];
end

% ---- Disclaimer & Footer --------------------------------------------
html = [html ...
'<div class="disclaimer">' newline ...
'  <strong>IMPORTANT DISCLAIMER:</strong> This report is an AI-assisted screening result generated by RetinaGuard (Prototype v1.0).' newline ...
'  It is NOT a substitute for examination by a qualified ophthalmologist.' newline ...
'  All findings must be confirmed by a licensed medical professional before clinical decisions are made.' newline ...
'  This system has not received regulatory approval for clinical deployment.' newline ...
'</div>' newline ...
'<div class="footer">RetinaGuard &mdash; AI-Assisted DR Screening Prototype &mdash; SIH 2026</div>' newline ...
'</div></body></html>'];

% ---- Write file -----------------------------------------------------
fid = fopen(reportPath, 'w', 'n', 'UTF-8');
if fid < 0
    error('generateReport: cannot write to %s', reportPath);
end
fprintf(fid, '%s', html);
fclose(fid);

end
