function cases = getDemoCases()
% getDemoCases  Returns the 6 built-in demo screening cases.
%
%   cases = getDemoCases()
%
%   Each case is a struct:
%     .id            - Demo case identifier
%     .label         - Human-readable label
%     .drGrade       - 0–4 DR grade
%     .quality       - Quality struct (score, focus, illum, fov, status)
%     .findings      - Lesion findings struct
%     .structures    - Structure detections struct
%     .confidence    - Overall model confidence (0–1)
%     .imageSynth    - Parameters to generate a synthetic fundus image
%     .description   - Clinical description (demo only)
%
%   DEMO NOTE: All cases use synthesized retinal images generated by
%   generateSyntheticFundus.m.  Results are NOT medically validated.

cfg = RGConfig();
sampleDir = fullfile(cfg.paths.root, 'demo', 'sample_images');

% ---- Case 1: Healthy retina, No DR ---------------------------------
c1.id          = 'DEMO-001';
c1.label       = 'Normal Retina — No DR';
c1.drGrade     = 0;
c1.quality     = makeQuality(88, 'Good','Good','Good','GOOD');
c1.findings    = makeFindings(false,0.97, false,0.95, false,0.96, false,0.98);
c1.structures  = makeStructures(true,0.94, true,0.91, true,0.93);
c1.confidence  = 0.93;
c1.description = 'Healthy retinal image with clear disc and macula. No lesions detected.';
c1.imageFile   = fullfile(sampleDir, 'demo_case1_grade0.png');
c1.imageSynth  = struct('lesionCount',0,'noiseLevel',0.02,'illumination','normal');

% ---- Case 2: Mild NPDR -------------------------------------------
c2.id          = 'DEMO-002';
c2.label       = 'Mild Non-Proliferative DR';
c2.drGrade     = 1;
c2.quality     = makeQuality(85, 'Good','Good','Good','GOOD');
c2.findings    = makeFindings(true,0.78, false,0.88, false,0.91, false,0.95);
c2.structures  = makeStructures(true,0.92, true,0.88, true,0.90);
c2.confidence  = 0.87;
c2.description = 'Microaneurysms detected. No exudates or hemorrhages. Consistent with mild NPDR.';
c2.imageFile   = fullfile(sampleDir, 'demo_case2_grade1.png');
c2.imageSynth  = struct('lesionCount',5,'noiseLevel',0.03,'illumination','normal');

% ---- Case 3: Moderate NPDR ----------------------------------------
c3.id          = 'DEMO-003';
c3.label       = 'Moderate Non-Proliferative DR';
c3.drGrade     = 2;
c3.quality     = makeQuality(82, 'Good','Good','Good','GOOD');
c3.findings    = makeFindings(true,0.91, true,0.87, false,0.94, false,0.93);
c3.structures  = makeStructures(true,0.91, true,0.85, true,0.89);
c3.confidence  = 0.91;
c3.description = 'Microaneurysms and hard exudates detected. No hemorrhage. Moderate NPDR.';
c3.imageFile   = fullfile(sampleDir, 'demo_case3_grade2.png');
c3.imageSynth  = struct('lesionCount',12,'noiseLevel',0.03,'illumination','normal');

% ---- Case 4: Severe NPDR ------------------------------------------
c4.id          = 'DEMO-004';
c4.label       = 'Severe Non-Proliferative DR';
c4.drGrade     = 3;
c4.quality     = makeQuality(79, 'Good','Acceptable','Good','GOOD');
c4.findings    = makeFindings(true,0.94, true,0.91, true,0.88, false,0.81);
c4.structures  = makeStructures(true,0.88, true,0.82, true,0.87);
c4.confidence  = 0.88;
c4.description = 'Multiple microaneurysms, exudates, and hemorrhages detected. Severe NPDR.';
c4.imageFile   = fullfile(sampleDir, 'demo_case4_grade3.png');
c4.imageSynth  = struct('lesionCount',25,'noiseLevel',0.04,'illumination','slightly_dark');

% ---- Case 5: Proliferative DR --------------------------------------
c5.id          = 'DEMO-005';
c5.label       = 'Proliferative Diabetic Retinopathy';
c5.drGrade     = 4;
c5.quality     = makeQuality(76, 'Good','Acceptable','Good','GOOD');
c5.findings    = makeFindings(true,0.96, true,0.93, true,0.91, true,0.84);
c5.structures  = makeStructures(true,0.85, true,0.79, true,0.88);
c5.confidence  = 0.86;
c5.description = 'Extensive lesions including neovascularization. Proliferative DR. Urgent referral required.';
c5.imageFile   = fullfile(sampleDir, 'demo_case5_grade4.png');
c5.imageSynth  = struct('lesionCount',40,'noiseLevel',0.05,'illumination','slightly_dark');

% ---- Case 6: Ungradable image --------------------------------------
c6.id          = 'DEMO-006';
c6.label       = 'Poor Quality — Ungradable';
c6.drGrade     = -1;   % -1 = ungradable
c6.quality     = makeQuality(28, 'Poor','Poor','Poor','UNGRADABLE');
c6.quality.reason          = 'Image is too blurry to grade.';
c6.quality.recommendation  = 'Recapture retinal image with improved focus and illumination.';
c6.findings    = [];
c6.structures  = [];
c6.confidence  = 0;
c6.description = 'Image quality insufficient for grading. Recapture required.';
c6.imageFile   = fullfile(sampleDir, 'demo_case6_ungradable.png');
c6.imageSynth  = struct('lesionCount',0,'noiseLevel',0.35,'illumination','dark');

cases = {c1; c2; c3; c4; c5; c6};
end

% =========================================================================
%  Helper constructors
% =========================================================================

function q = makeQuality(score, focus, illum, fov, status)
q.score           = score;
q.focus           = focus;
q.illumination    = illum;
q.fieldOfView     = fov;
q.contrast        = 'Acceptable';
q.retinalVisibility = 'Good';
q.status          = status;  % 'GOOD' | 'BORDERLINE' | 'UNGRADABLE'
q.reason          = '';
q.recommendation  = '';
end

function f = makeFindings(maDetect, maConf, exDetect, exConf, heDetect, heConf, nvDetect, nvConf)
f.microaneurysm.detected    = maDetect;
f.microaneurysm.confidence  = maConf;
f.exudate.detected          = exDetect;
f.exudate.confidence        = exConf;
f.hemorrhage.detected       = heDetect;
f.hemorrhage.confidence     = heConf;
f.neovascularization.detected   = nvDetect;
f.neovascularization.confidence = nvConf;
end

function s = makeStructures(odDetect, odConf, fvDetect, fvConf, vsDetect, vsConf)
s.opticDisc.detected    = odDetect;
s.opticDisc.confidence  = odConf;
s.fovea.detected        = fvDetect;
s.fovea.confidence      = fvConf;
s.vessels.detected      = vsDetect;
s.vessels.confidence    = vsConf;
end
